### ISSUE TITLE
Feature Request: Auto create render directory folders if they don't previously exist

### ISSUE THREAD

**Issue by bbmn** [oh-wo/nuke-watcher#2]
Would like the script to check if _ToRender, Complete and Failed folders already exist in the defined output directory and if not auto generate them before sending the script and rendering.

**Comment by oh-wo** [comment]
@bbmn I think it already does this doesn't it?

**Comment by bbmn** [comment]
I just deleted the Complete and Failed folders to test and they don't auto generate again. They did initially I believe?

**Comment by oh-wo** [comment]
Did you restart nuke-watcher?

**Comment by bbmn** [comment]
Ahh yes I see. Restarted nuke-watcher and it generated 'Complete' and 'Failed' folders. This would eventually be mitigated when the nuke-watcher script is initiated via Nuke.

**Comment by oh-wo** [comment]
Was the behaviour you're after for the folders to be regenerated whenever a file is dropped in?

Probably makes sense.

**Comment by bbmn** [comment]
Not neccesarily but if by accident a user deletes or renames those folders after they are generated then the render will fail and the user might not be able to tell why. 

So a check and generate/ regenerate from the push of the Nuke button would be nice.

**Comment by oh-wo** [comment]
Fixed in version 1.11: `npm i -g nuke-watcher@1.0.11`
